### ISSUE TITLE
bottom_sheet_message_layout

### ISSUE THREAD

**Issue by pkgundam** [Kennyc1012/BottomSheet#22]
in bottom_sheet_message_layout.xml, the id is not defined correctly. + is missing and it is causing issue during build . Could you please look into it.

**Comment by pkgundam** [comment]
Hi, thank you for fixing the issue.

Here is the issue when creating the bottom sheet.

12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime: FATAL EXCEPTION: main
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime: Process: com.maichef.app, PID: 9671
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime: java.lang.IllegalStateException: Could not execute method for android:onClick
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:275)
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at android.view.View.performClick(View.java:4780)
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:19866)
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254)
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:  Caused by: java.lang.reflect.InvocationTargetException
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:270)
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at android.view.View.performClick(View.java:4780) 
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:19866) 
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739) 
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95) 
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135) 
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254) 
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:  Caused by: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at android.view.ViewRootImpl.setView(ViewRootImpl.java:566)
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:282)
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at android.app.Dialog.show(Dialog.java:298)
12-22 21:31:57.615 9671-9671/com.maichef.app E/AndroidRuntime:     at com.kennyc.bottomsheet.BottomSheet$Builder.show(BottomSheet.java:880)


I tried to open the bottom sheet in two ways

View view1 = getLayoutInflater().inflate(R.layout.bottom_sheet_layout, null);
        BottomSheet.Builder sheet = new BottomSheet.Builder(getApplicationContext()).setView(view1);
        sheet.show();

and

BottomSheet.Builder sheet = new BottomSheet.Builder(getApplicationContext())
                .setTitle("Title")
                .setMessage(message)
                .setPositiveButton("OK")
                .setNegativeButton("CLOSE")
                .setIcon(ContextCompat.getDrawable(getApplicationContext(), R.drawable.ic_close))
                .setListener(new BottomSheetListener() {
                    @Override
                    public void onSheetShown() {

                    }

                    @Override
                    public void onSheetItemSelected(MenuItem menuItem) {

                    }

                    @Override
                    public void onSheetDismissed(int i) {
                        L.T(getApplicationContext(), i + "");
                    }
                });
        sheet.show();

**Comment by pkgundam** [comment]
thank you Kenny.
