### ISSUE TITLE
Menu items

### ISSUE THREAD

**Issue by JackRoberts1998** [Kennyc1012/BottomSheet#34]
Hi i really like the bottomsheet it looks great i'm working on a web browser and i've implemented it to launch an app from a web url but i've got a problem with the bottom sheet items not working or crashing when you load it from shouldOverrideUrlLoading i have attached the code so you can see and when i click these items the app crashes can you give me any suggestions ?

**Comment by JackRoberts1998** [comment]
07-03 16:01:52.592 13877-13877/com.jackroberts.orion D/Orion :: Added to historycom.jackroberts.orion.History@bb1adc3
07-03 16:01:52.606 13877-13877/com.jackroberts.orion D/Orion :: Added to historycom.jackroberts.orion.History@f7636be
07-03 16:02:00.498 13877-13877/com.jackroberts.orion D/AndroidRuntime: Shutting down VM
07-03 16:02:00.499 13877-13877/com.jackroberts.orion E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.jackroberts.orion, PID: 13877
                                                                       java.lang.NullPointerException: uriString
                                                                           at android.net.Uri$StringUri.<init>(Uri.java:475)
                                                                           at android.net.Uri$StringUri.<init>(Uri.java)
                                                                           at android.net.Uri.parse(Uri.java:437)
                                                                           at com.jackroberts.orion.MainActivity$WebClient.onSheetItemSelected(MainActivity.java:962)
                                                                           at com.kennyc.bottomsheet.BottomSheet.onItemClick(BottomSheet.java:350)
                                                                           at android.widget.AdapterView.performItemClick(AdapterView.java:310)
                                                                           at android.widget.AbsListView.performItemClick(AbsListView.java:1155)
                                                                           at android.widget.AbsListView$PerformClick.run(AbsListView.java:3096)
                                                                           at android.widget.AbsListView$3.run(AbsListView.java:4011)
                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6044)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by Kennyc1012** [comment]
This looks like an issue with the Uri string being null, not the library

**Comment by JackRoberts1998** [comment]
is there a way to put the onSheetItemSelected items in the same area as calling the bottom sheet
