### ISSUE TITLE
A sheet crashes when using vector icon

### ISSUE THREAD

**Issue by aratn0n** [Kennyc1012/BottomSheet#43]
I got this error when I uses vector icon in a menu

```
android.content.res.Resources$NotFoundException: File res/drawable-hdpi-v4/ic_translate_grey_48dp.xml from drawable resource ID #0x7f02008d. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
	at android.content.res.Resources.loadDrawable(Resources.java:2600)
	at android.content.res.Resources.getDrawable(Resources.java:795)
	at com.kennyc.bottomsheet.b.b.setIcon(Unknown Source)
	at android.view.MenuInflater$MenuState.setItem(MenuInflater.java:399)
	at android.view.MenuInflater$MenuState.addItem(MenuInflater.java:451)
	at android.view.MenuInflater.parseMenu(MenuInflater.java:188)
	at android.view.MenuInflater.inflate(MenuInflater.java:110)
```

**Comment by Kennyc1012** [comment]
Please use the 2.3.4 release and let me know if the issue persists. I was unable to reproduce it using that build.

**Comment by aratn0n** [comment]
Hi, I'm so sorry from being late. The crash only happen on my KitKat Device. I already tried 2.3.4, but it still has this problem.
